# Generated by Django 4.2.4 on 2023-08-29 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_1_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='throw_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 21, 0, 10, 690353)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_create', models.DateField(auto_now=True)),
                ('date_change', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_1_app.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_1_app.post')),
            ],
        ),
    ]
