# Generated by Django 4.2.4 on 2023-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='common_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
